### ISSUE TITLE
MUTO-INTL Revoke clinical data that is in the "invalid" state due to dictionary 1.13 release

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#856] opened 2021-12-14 19:23 UTC
- With the release of Dictionary 1.13, MUTO-INTL clinical data has been invalidated. 
  - "Unknown" is not longer allowed for Vital Status.  
- We do not have an automated or user-facing process to rectify this, so this data will have to be removed via a backdoor into the platform by a developer. 
- Final state: data will be registered, but empty, since this data can never be fixed. 

Proposal: 
- Data migration will be required. Clinical supports this. Flyway?

**Comment by akachru-github** [comment] 2021-12-16 16:54
Requires meeting with @hknahal , @blabadi , @joneubank before pointing.

**Comment by akachru-github** [comment] 2021-12-20 17:07
- Since the clinical data will never be able to be fixed, this presents a unique situation for the platform
- We will not be removing registered IDs as they map to metadata files in Song. 
- We don't want this data to show up in the dashboard
- We will need to add a state / flag of some kind to "invalid" clinical data that **will never be fixed**

Short term:
- manually remove the submitted data but keeping their registration. Keep the donors registered and remove the clinical data.  
  - displayed as donors with registered samples with no data. 
  - Will need to define the technical approach to do this (cc. @blabadi , @joneubank)
- We will enforce the clinical / molecular data requirements and not release the matching molecular data. **This is NOT an exception**


Long term proposals (if we feel it's needed)
- New state for invalid donors to acknowledge they are invalid and will never be fixed and clears them accordingly.
- We are generally aiming to NOT change the core clinical data... but this may happen again in the future. We try to actively minimize those changes. 
- potentially start talking about "resetting donors" -> keeping them registered, but removing the clinical data for them. Cleaning the slate. 
- Also discuss this in conjunction with the **"Clinical Exceptions"** feature.

**Comment by b-f-chan** [comment] 2022-05-19 15:37
~220 donors still invalid --> If they get clinical exception for this field no issue, but right now cannot sign off on their submission

**Comment by b-f-chan** [comment] 2022-05-19 15:39
@hknahal - Review ticket for validity since it has been around for a while, then provide recommendation - E.g. Are donors missing other core clinical fields also

**Comment by hknahal** [comment] 2022-05-19 16:15
@b-f-chan Confirmed the 220 donors do not have any other clinical data (ie. no specimen, treatment, followup etc. data). They only submitted the `Donor` schema for these 220 donors and are missing the `vital_status` field. We should remove these 220 donors to unblock them so they can sign off on the rest of their clinical submission (they submitted 5 donors with other valid clinical data).

**Comment by b-f-chan** [comment] 2022-05-31 13:32
Possibly similar to the SOPs @blabadi has been working on with some variation - Need to check

Ideally get done before workshop on June 13

**Comment by b-f-chan** [comment] 2022-06-13 15:47
@hknahal - Any update on whether MUTO-INTL has DACO access resolved yet?  I won't ask the team to proceed with this until they are unblocked, moving to next sprint

**Comment by hknahal** [comment] 2022-06-13 15:52
@b-f-chan I haven't heard back from the MUTO-INTL program, but I followed up with them again today, so hoping we can find out the status of their DACO access soon.

**Comment by Buwujiu** [comment] 2022-06-30 15:27
Need further confirmation from MUTO-INTL.

**Comment by b-f-chan** [comment] 2022-08-31 15:11
Last CMD-Working Group Meeting we agreed on Program Level Exceptions to start; also needed to share with them some proposed dictionary changes.

In meantime getting feedback from MOH group and it came up how to handle Lost to Follow-Up.  Relates to this ticket due to the Vital Status.  They know what their last Vital Status was, but have lost them to follow-up.  Related to ticket https://github.com/icgc-argo/argo-dictionary/issues/358.  There's also additional use cases needed.

**Comment by Buwujiu** [comment] 2022-12-01 15:28
once dictionary #358 is complete, will unblock mutograph.

**Closed as completed** 2023-05-18 13:52 UTC
Labels: bug
