### ISSUE TITLE
Configure and Deploy SFTP for Working Group Transfers 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#753] opened 2021-03-29 13:52 UTC
- Need a SFTP.  The working groups need to share intermediate files that they produce, and must do this in a secured manner.
- Requirement is that whoever accesses it should be part of the working group, AND should have access to DACO 

Examples out there:
- Barcelona uses [Owncloud](https://owncloud.com/), example implementation here: http://ftp.life.bsc.es/index.php/login?redirect_url=%252Findex.php%252Fapps%252Ffiles%252F%253Fdir%253D%252F%2526fileid%253D153869
- ICGC 25K did this with the submission system. 
------
Update Feb 23 2022: 
- Dusan started this: https://github.com/overture-stack/pensato
- Confirmed that this satisfies the business need
- This ticket is tracking the configuration and deployment to production.

**Comment by akachru-github** [comment] 2022-03-10 16:49
Demo coming up in ~2 weeks. This will need to be deployed and configured.

**Comment by akachru-github** [comment] 2022-03-10 16:57
- RDPC prod cluster
- obj storage needs to be set up to hold shared data. cc. @henro001 
- Helm chart configured to deploy pensato
- jenkins provision and deploy jobs set up to deploy pensato.

**Comment by akachru-github** [comment] 2022-04-07 15:38
@joneubank  to speak to @henro001  on any blockers on getting this to production.

**Comment by akachru-github** [comment] 2022-04-07 15:41
1. need a list of users to give permissions to. Lincoln may have this list. 
2. write down instructions for how to access and use. @joneubank  can write steps, and perhaps Lincoln can do the comms out to the working groups.

**Comment by b-f-chan** [comment] 2022-04-25 19:34
Update after discussions between @joneubank and @blabadi 

For Pensato to work with the current code, it requires Ego APIs to be available to it that, and those APIs should be secured and unavailable.

So two action items arise from this:

1.  Find out why the APIs became exposed in the newer Ego version
2. Update Pensato code to not require them

This may need a small code change, moving this back to In Progress

**Comment by blabadi** [comment] 2022-04-29 16:11
update on point 1, it seems that EGO is working as intended in version 5, that's based on this code 
https://github.com/overture-stack/ego/blob/9fec7c107899ebbf09f77ec02a8c60da574805a8/src/main/java/bio/overture/ego/security/JWTAuthorizationFilter.java#L77-L78
it was intended for applications to use basic authentication, so the fact that ego 4.x wasn't working seems like a bug to me
when application client credentials got introduced later the else statement included applications 

That's said we want to move away from basic authentication so point 2 still holds

**Comment by b-f-chan** [comment] 2022-05-06 02:33
This is priority 1 for @joneubank this sprint; to check if can offload this task to anyone else in future

**Comment by b-f-chan** [comment] 2022-05-19 12:04
Deployed to prod, presented demo to working group members, closing

**Closed as completed by b-f-chan** 2022-05-19 12:04 UTC
Labels: specs-needed, critical
