### ISSUE TITLE
icgcargo / daco2ego: Migrate from Dockerhub to Github Packages

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#624] opened 2020-11-11 18:39 UTC

**Comment by yalturmes** [comment] 2021-08-19 13:27
All confusion with branches aside, looks like the image was already being published to the ghcr registry.
Jenkinsfile was updated to remove leftovers from outdated DIND instructions.

Next up:
- Communicate changes with @rosibaj 
- Provide details for redeploying image to the IT team
- Image:tag to use for redeployment - `ghcr.io/icgc-argo/daco2ego:d750ab5`

**Comment by b-f-chan** [comment] 2021-08-20 14:11
Fixed, image published, just waiting for Monday for confirmation there's no issues after redeploy

Check with @rosibaj if any formal testing required or just confirm nothing is breaking

**Comment by rosibaj** [comment] 2021-08-20 14:26
no formal testing - just need to make sure it works over the next 2-3 days!

**Comment by yalturmes** [comment] 2021-08-23 15:15
Updated Daco2ego image has been redeployed by the IT team. 
@rosibaj confirmed service looks healthy after redeployment.
Closing ticket.

**Closed as completed by yalturmes** 2021-08-23 15:15 UTC
